### PR TITLE
Some performance considerations, code style cleanup, added rail fence implementation (see #23), updated caesar method for shift fallback, added atbash cipher implementation, and added documentation

### PR DESCRIPTION
**Pull request by jakewilliami**

### CODE REVIEW

**Comment by Smaug123** [comment]
Thanks for this! I'm not maintaining the library at the moment, but would be happy to make you a collaborator if you like.

**Comment by jakewilliami** [comment]
@Smaug123 That'd be good, as I am happy to maintain it (it is relatively small) :-)

**Comment by jakewilliami** [comment]
Oops, just realised that your `monoalphabetic` is my `substitution` >.<  We need to make a decision whose to keep.

I think we should keep yours.  Indeed, it is faster for encryption:
```julia
julia> @btime encrypt_monoalphabetic("THIS CODE WAS INVENTED BY JULIUS CAESAR", "DEFGHIJKLMNOPQRSTUVWXYZABC")
  2.887 μs (22 allocations: 2.59 KiB)
"WKLV FRGH ZDV LQYHQWHG EB MXOLXV FDHVDU"

julia> @btime encrypt_substitution("THIS CODE WAS INVENTED BY JULIUS CAESAR", "DEFGHIJKLMNOPQRSTUVWXYZABC")
  3.516 μs (27 allocations: 2.72 KiB)
"WKLV FRGH ZDV LQYHQWHG EB MXOLXV FDHVDU"

julia> @btime decrypt_monoalphabetic("WKLV FRGH ZDV LQYHQWHG EB MXOLXV FDHVDU", "DEFGHIJKLMNOPQRSTUVWXYZABC")
  10.752 μs (99 allocations: 7.19 KiB)
"this code was invented by julius caesar"

julia> @btime decrypt_substitution("WKLV FRGH ZDV LQYHQWHG EB MXOLXV FDHVDU", "DEFGHIJKLMNOPQRSTUVWXYZABC")
  4.094 μs (34 allocations: 4.00 KiB)
"this code was invented by julius caesar"
```

Though, I am unsure if `monoalphabetic` is the best function name, as it is the substitution cipher?  What do you think?

I will also add some methods to your code that I implemented in mine, as they might be useful.

Sorry for this confusion!  I can sort all of this out if you allow me to be a contributor.  I have also been working on publishing documentation for this, instead of having it in the REAME.  Let me know what you think :-)

**Comment by jakewilliami** [comment]
Okay, I've just pushed some documentation.  There are two more things that need to be done to see the documentation:
  - Delete `.travis.yml` (I have set up the documentation to deploy from GitHub Actions); and
  - Go to `Settings > Options > GitHub Pages`, and select the `gh-pages` branch, then press save. This will allow GitHub Pages to access the `gh-pages` branch created by `Documenter.jl`.

The docs will then be accessible at [https://Smaug123.github.io/ClassicalCiphers.jl/dev/](https://Smaug123.github.io/ClassicalCiphers.jl/dev/).  I have added a tag to the top of the README for people to click on to take them to the docs :-)

**Comment by Smaug123** [comment]
Thanks for this - I've invited you to be a collaborator.

I prefer the name `monoalphabetic` because there are *polyalphabetic* substitution ciphers which are different.

Your `decrypt` is much faster than mine - how about replacing my `decrypt` with yours, and keeping my `encrypt`? :P

**Comment by jakewilliami** [comment]
Thank you for allowing me to collaborate @Smaug123! 

Actually, all of our code is very similar, I'm surprised it's not much more similar timings!  I will replace your `decrypt` with my `encrypt` very soon, and remove `substitution.jl`!  Sorry for the mix up!

Would you like to merge this request now, or shall I?

**Comment by jakewilliami** [comment]
Right!  I have merged `substitution.jl` into `monoalphabetic.jl` as of 938d326.  We have the best of both worlds regarding benchmarking:

```julia
julia> @btime encrypt_monoalphabetic("THIS CODE WAS INVENTED BY JULIUS CAESAR", "DEFGHIJKLMNOPQRSTUVWXYZABC")
  2.746 μs (21 allocations: 2.31 KiB)
"WKLV FRGH ZDV LQYHQWHG EB MXOLXV FDHVDU"

julia> @btime decrypt_monoalphabetic("WKLV FRGH ZDV LQYHQWHG EB MXOLXV FDHVDU", "DEFGHIJKLMNOPQRSTUVWXYZABC")
  3.817 μs (31 allocations: 3.81 KiB)
"this code was invented by julius caesar"
```

I am going to merge this now—I hope that's alright!  Have tested everything as I go on my end, and CI on my fork hasn't found any errors :-)

**Comment by Smaug123** [comment]
Yep, happy for you to go ahead with whatever you want. Thanks for fixing things up!

**Comment by jakewilliami** [comment]
Thanks @Smaug123!  

> Go to Settings > Options > GitHub Pages, and select the gh-pages branch, then press save. This will allow GitHub Pages to access the gh-pages branch created by Documenter.jl.

This is all that is left to do for documentation to be deployed, I believe.

**Comment by Smaug123** [comment]
Just having a look around my settings - currently it's set up to serve on www.patrickstevens.co.uk for some reason. I'm currently quite busy, but will hopefully get a chance to deal with this by tonight.

**Comment by jakewilliami** [comment]
No worries, thank you!

**Pull request merged**
